# Site settings
title:          /t>
description:    "Um blog minimo de programação"
baseurl:        "/blog"
url:            "https://othiagob.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Thiago S. Borghardt
  # url:          https://chester.how
  email:       	thiago.mobdev@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Theme
remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
